install.packages("tidyverse")
install.packages("readxl")
install.packages("readr")
install.packages("wget")
install.packages("dplyr")
install.packages("sqldf")
install.packages("janitor")
library(tidyverse)
library(readr)
library(readxl)
library(wget) #THIS REQUIRES WGET ON YOU MAC OR WINDOWS BEING INSTALLED... OTHERWISE USE R.DOWNLOAD.FILE
library(dplyr)
library(sqldf)
library(janitor)
download.file("https://cyrusjones159.github.io/Cockey-Investments/Financials/FinancialsScreener_results.xls", "c:\\users\\stritzj\\Documents\\542\\financials2.xls", mode = "wb")
mydf <- read_excel("c:/users/stritzj/Documents/542/financials2.xls")
head(mydf, 5)
str(mydf)

mydf2 <- clean_names(mydf)
head(mydf2, 5)
result <- sqldf("SELECT * FROM mydf2 WHERE company_name = 'Bank OZK'")
result2 <- sqldf("SELECT symbol, dividend_yield FROM mydf2 WHERE dividend_yield > 4 Order by dividend_yield DESC")
head(result,5)
result2
